// portfolio/src/components/Footer.tsx
export const Footer = () => {
    return (
        <footer className="flex justify-center items-center p-4 text-white bg-[var(--color-2)]">
            <div className="text-center mx-auto">
                <ul className="list-none flex justify-center mb-3 [&_li]:transition-transform [&_li]:hover:scale-110">
                    <li className="mx-3">
                        <a href="#" target="_blank" rel="noopener" aria-label="Facebook">
                            <i className="fa-brands fa-facebook"></i>
                        </a>
                    </li>
                    <li className="mx-3">
                        <a href="https://www.instagram.com/luiz_gabr1el/" target="_blank" rel="noopener" aria-label="Instagram">
                            <i className="fa-brands fa-instagram"></i>
                        </a>
                    </li>
                    <li className="mx-3">
                        <a href="https://github.com/LuizBuarqueDev" target="_blank" rel="noopener" aria-label="GitHub">
                            <i className="fa-brands fa-github"></i>
                        </a>
                    </li>
                    <li className="mx-3">
                        <a href="https://www.linkedin.com/in/luiz-gabriel-buarque-vasconcelos-24074328b/" target="_blank" rel="noopener" aria-label="Linkedin">
                            <i className="fa-brands fa-linkedin"></i>
                        </a>
                    </li>
                </ul>

                <div>
                    <div>
                        Email:{" "}
                        <a href="mailto:luizgabrielbuarque@gmail.com">
                            luizgabrielbuarque@gmail.com
                        </a>
                    </div>
                    <div>
                        Telefone:{" "}
                        <a href="tel:+5581996346840">
                            (81) 99634-6840
                        </a>
                    </div>
                    <div className="mt-2">&copy; 2026 Luiz Gabriel. Todos os direitos reservados.</div>
                </div>
            </div>
        </footer>
    );
}

// portifolio/src/components/Footer.vue
<script>
</script>

<template>
  <footer class="text-white py-5">
    <div class="container text-center">
      <ul class="list-unstyled d-flex justify-content-center mb-3">
        <li class="mx-3">
          <a href="#" target="_blank" rel="noopener" aria-label="Facebook">
            <i class="fa-brands fa-facebook"></i>
          </a>
        </li>
        <li class="mx-3">
          <a href="#" target="_blank" rel="noopener" aria-label="Instagram">
            <i class="fa-brands fa-instagram"></i>
          </a>
        </li>
        <li class="mx-3">
          <a href="#" target="_blank" rel="noopener" aria-label="GitHub">
            <i class="fa-brands fa-github"></i>
          </a>
        </li>
                <li class="mx-3">
          <a href="#" target="_blank" rel="noopener" aria-label="Linkedin">
            <i class="fa-brands fa-linkedin"></i>
          </a>
        </li>
      </ul>

      <div>
        <div>Email: <a href="mailto:luizgabrielbuarque@gmail.com">luizgabrielbuarque@gmail.com</a></div>
        <div>Telefone: <a href="tel:+5581996346840">(81) 99634-6840</a></div>
        <div class="mt-2">&copy; 2025 Luiz Gabriel. Todos os direitos reservados.</div>
      </div>
    </div>
  </footer>
</template>

<style lang="scss" scoped>
footer {
  bottom: 0;
  left: 0;
  width: 100%;
  background-color: var(--color_2);

  a {
    color: var(--color_5);
    text-decoration: none;

    &:hover {
      color: var(--color_5_hover);
    }

    i {
        font-size: 1.5em;
    }
  }
}
</style>
