// portifolio/src/components/Header.vue
<script setup>

</script>

<template>
    <header class="d-flex justify-content-between align-items-center">
        <aside class="ms-5 m-2">
            <router-link to="/">&lt;LG /&gt;</router-link>
        </aside>

        <ul class="d-flex list-unstyled me-5 gap-5 m-0">
            <li><router-link to="/"> <i class="fa-brands fa-github"></i> Github </router-link></li>
            <li><router-link to="/"> <i class="fa-brands fa-linkedin"></i> Linkedin </router-link></li>
            <li><router-link to="/"> <i class="fa-solid fa-envelope"></i> E-mail </router-link></li>
        </ul>
    </header>
</template>

<style lang="scss" scoped>
header {
    background: var(--gradient_1);

    a {
        text-decoration: none;
        display: inline-block;
        padding: 10px;
        border-radius: 8px;
        color: var(--color_5);
        transition: all 0.2s ease;

        &:hover {
            transform: scale(1.05);
            background-color: var(--color_1_hover);
            color: var(--color_5_hover);
        }
    }

    aside {
        font-family: "Share Tech", sans-serif;
        font-size: 1.8em;
    }
}
</style>

// portfolio/src/components/Header.tsx
import Link from "next/link";

export const Header = () => {
  return (
<header className="flex justify-between items-center p-4">
  <Link href={"/"} className="flex items-center gap-2">
<i className="fa-solid fa-house text-xl !block sm:!hidden"></i>
<h3 className="hidden sm:!block">@LuizBuarqueDev</h3>
  </Link>



      <nav>
        <ul className="flex gap-10 items-center [&_i]:text-2xl [&_li]:transition-transform [&_li]:hover:scale-110 [&_li]:hover:border-b-2 [&_li]:hover:border-white">
          <li>
            <a href="https://github.com/LuizBuarqueDev" target="_blank" rel="noopener noreferrer" className="flex items-center gap-2">
              <i className="fa-brands fa-github"></i>
              <span className="hidden sm:inline">Github</span>
            </a>
          </li>
          <li>
            <a href="https://www.linkedin.com/in/luiz-gabriel-buarque-vasconcelos-24074328b/" target="_blank" rel="noopener noreferrer" className="flex items-center gap-2">
              <i className="fa-brands fa-linkedin"></i>
              <span className="hidden sm:inline">Linkedin</span>
            </a>
          </li>
          <li>
            <a href="mailto:luizgabrielbuarque@gmail.com" target="_blank" rel="noopener noreferrer" className="flex items-center gap-2">
              <i className="fa-solid fa-envelope"></i>
              <span className="hidden sm:inline">E-mail</span>
            </a>
          </li>
          <li>
            <Link href="/certificates" className="flex items-center gap-2">
              <i className="fa-solid fa-certificate"></i>
              <span className="hidden sm:inline">Certificados</span>
            </Link>
          </li>
        </ul>
      </nav>
    </header>
  );
}
