// portfolio/src/app/page.tsx
import { Footer } from "@/components/Foooter";
import { Header } from "@/components/Header";
import { Presentation } from "@/components/Presentation";

export default function Home() {
  return (
    <div>
        <Header />
      <main className="flex">
        <Presentation />
      </main>
      <Footer />
    </div>
  );
}

// portifolio/src/App.vue
<script setup>
import { RouterLink, RouterView } from 'vue-router'

import Header from '@/components/Header.vue';
import Footer from '@/components/Footer.vue';
import Json from '@/components/Json.vue';
</script>

<template>
  <Header/>
  <RouterView />
  <Json/>
  <Footer/>
</template>

<style scoped>
</style>
